apple/containerization

- README.md
Not to be pedantic, but "light weight" is usually considered to be one word.
> Update README.md with minor correction

- README.md
This PR requires installing Xcode 26 beta until we resolve https://github.com/apple/containerization/issues/66.
> Require having Xcode 26 beta

- Sources/cctl/RunCommand.swift
We already have a type that does what the setupSigwinchHandler method was doing.
> cctl: Use AsyncSignalHandler for sigwinch

- .github/workflows/release.yml
Matches changes made in https://github.com/apple/container/pull/187 by @Thedarkmatter10
> Improve release tag regex

- Sources/Containerization/LinuxProcess.swift
We should return our own error type always for our methods. This wraps all of the public methods on the process to return a more full featured error than the rpcerrors we get today.
> LinuxProcess: Always return CZError

- Sources/ContainerizationOCI/Client/LocalOCILayoutClient.swift
- Sources/ContainerizationOCI/Client/RegistryClient+Fetch.swift
We were doing intermediate step copies to Data objects both for push and pull. We only need the data for the lifetime of the singular writes to update the state of the checksums and to write to disk somewhere, so we can use a view into the buffer from the http client to satisfy this.
> ContainerizationOCI: Cut down on allocations

- Sources/ContainerizationOCI/Client/RegistryClient.swift
- Tests/ContainerizationOCITests/RegistryClientTests.swift
Fixes https://github.com/apple/container/issues/182 and https://github.com/apple/container/issues/183
> Adds some context to fetchToken errors

- .github/workflows/containerization-build-template.yml
- Package.swift
- Sources/Containerization/NATNetworkInterface.swift
- scripts/make-docs.sh
This PR removes the no longer needed support for `CURRENT_SDK`.
> Remove the support for `CURRENT_SDK`

- .github/ISSUE_TEMPLATE/01-bug.yml
- .github/ISSUE_TEMPLATE/02-feature.yml
Matches https://github.com/apple/container/pull/258
> Switch to using issue types for bugs and features

- vminitd/Sources/vminitd/ManagedProcess.swift
The two starting and exiting logs I feel are important enough to get promoted to info level.
> Vminitd: Change some process log levels

- Makefile
- vminitd/Makefile
Added "" around some paths so that spaces in directory names will work
> Handle spaces in current dir by quoting paths

- Sources/Containerization/VZVirtualMachineInstance.swift
While this only supports AS, xcode's default will build all arches, so this presents a bit nicer default for Archiving an xcode application that utilizes containerization.
Fixes #179
> guard arch around Rosetta API

- Sources/ContainerizationOCI/Client/KeychainHelper.swift
This allows us to handle errors from lookup with only the keychain helper error types which simplifies the logic 
related https://github.com/apple/container/pull/331
> Handle keychain query errors in keychain helper lookup

- Sources/Containerization/LinuxContainer.swift
Crummy rebase that didn't pickup the Mutex changes
> LinuxContainer: Fix build break

- Sources/Containerization/LinuxContainer.swift
The state updates because of the way the macro works weren't actually being performed under the lock.
> LinuxContainer: Remove SendableProperty usage

- Sources/ContainerizationNetlink/NetlinkSession.swift
There's 82KiB of logs on every container launch for netlink, that may be a bit excessive 😄.
> Netlink: Change logging to trace level

- Sources/Containerization/VZVirtualMachineInstance.swift
- Sources/Containerization/VirtualMachineInstance.swift
- Sources/cctl/RunCommand.swift
The VirtualMachineInstance comment is not entirely true. It just represents a single VM.
> Misc. capitalization/comment adjustments

- Sources/Containerization/ContainerManager.swift
We should be able to supply an ImageStore if the user wants a different ContentStore, or a different path.
> ContainerManager: Make root/imagestore suppliable

- vminitd/Sources/vminitd/CgroupManager.swift
- vminitd/Sources/vminitd/ManagedContainer.swift
- vminitd/Sources/vminitd/ManagedProcess.swift
> vminitd: Rename CgroupManager -> Cgroup2Manager

- README.md
> add kernel support section to readme

- Sources/Containerization/ContainerManager.swift
- Sources/Containerization/Image/ImageStore/ImageStore+Export.swift
- Sources/Containerization/Image/ImageStore/ImageStore+Import.swift
- Sources/Containerization/NATNetworkInterface.swift
- Sources/Containerization/UnixSocketRelay.swift
- Sources/Containerization/VZVirtualMachineInstance.swift
- Sources/ContainerizationOS/AsyncSignalHandler.swift
- Sources/Integration/ProcessTests.swift
#288 accidentally reverted #282 and #284.
> Undo accidental revert of commits

- .github/ISSUE_TEMPLATE/01-bug.yml
This PR adds the default value "N/A" to the logs section to prevent it from being empty in most issues.
> Update an issue template

- vminitd/Sources/vminitd/Cgroup2Manager.swift
This is not wired up to anything right now, but it will be used for implementing stats gathering on the host via an rpc in the future. I've left off the rpc portion as this is already a decent amount to review.
> Vminitd: Add cgroup stats support

- Makefile
Add coverage target for getting csv code-coverage output
> make: add coverage target
