apple/containerization

.github/workflows/docs-release.yaml

We eventually only want to support building docs from release branches and tags, however, while we're working to initially set up the docs, we may have some churn. So we want to be able to publish from main during that churn.

Allow building docs from main

---

Tests/ContainerizationOCITests/RegistryClientTests.swift
Tests/ContainerizationTests/ImageTests/ImageStoreTests.swift

This removes two image push tests. We cannot have the CI push to our ghcr registry since external users do not have write access for pushing the image. We will explore a better solution.

Remove image push tests

---

CONTRIBUTING.md

Corrects a grammatical error in CONTRIBUTING.md line 36.
**Line 36**: `speed of which` → `speed at which`
The preposition "of" is incorrect when connecting the noun "speed" with the relative pronoun "which". Standard English requires "at" (e.g., "the speed at which", "the rate at which").
**Before:**
```
This will greatly help the priority setting and speed of which maintainers can get to your issue.
```
**After:**
```
This will greatly help the priority setting and speed at which maintainers can get to your issue.
```

Fix grammar: "speed of which" → "speed at which" in CONTRIBUTING.md

---

kernel/README.md

This change fixes a broken nested list and updates the phrase "light weight" for consistency with https://github.com/apple/containerization/pull/50.

docs: Fix typo and broken nested list in kernel/README.md

---

README.md

It'd be useful in the blurb about what APIs the project contains to link to where the source for these features live in the project.
I'm not too worried about link rot, as while the APIs in the packages may change over time, the package names I'd imagine will stay static. I've also left off a link for rosetta as we don't really have a central spot to toggle it, it's split across a couple files/packages.

Add links in README to the various products

---

README.md

#70 Made it clearer as I wasn't sure if the API allows us to run x64 binaries or also run such Docker images.

clarified linux/amd64 images support

---

README.md

This PR updates the names of Xcode and macOS to the official names used in https://developer.apple.com/download/applications/. Also, it fixes the capitalization in "Apple silicon".

Update the names of Xcode, macOS, and Apple silicon

---

CONTRIBUTING.md
README.md

Remove Latin abbreviations from the documentation in accordance with the [Apple Style Guide](https://help.apple.com/applestyleguide/). This change does not impact any abbreviations used in code comments since those are not covered by the style guide.

docs: Avoid using Latin abbreviations in documentation

---

Sources/Containerization/NATNetworkInterface.swift

This PR updates availability checks for macOS 16 to macOS 26.

Update availability checks to macOS 26

---

Sources/ContainerizationEXT4/EXT4+Export.swift
Tests/ContainerizationEXT4Tests/TestEXT4ExtendedAttributes.swift
Tests/ContainerizationEXT4Tests/TestFormatterUnpack.swift

- Corrected the typo in the method name (`Extened` → `Extended`)
- Updated all references to reflect the corrected spelling
- Introduced a `@available(*, deprecated)` alias for the original method to maintain backward compatibility, as it was part of the public API

Fix: `extended` in throughout the code

---

Sources/Integration/ProcessTests.swift
Sources/Integration/Suite.swift
Sources/cctl/RunCommand.swift
vminitd/Sources/vminitd/Server+GRPC.swift

Fixes #103 (and should fix https://github.com/apple/container/issues/108)
Today we only parse if the username field of the runtime spec is set, but this misses if someone just supplied the integer uid and gid fields only.

Vminitd: Always parse /etc/passwd

---

Sources/Containerization/LinuxProcess.swift
Sources/Integration/ProcessTests.swift
Sources/Integration/Suite.swift
vminitd/Sources/vminitd/ProcessSupervisor.swift
vminitd/Sources/vminitd/StandardIO.swift
vminitd/Sources/vminitd/TerminalIO.swift

This change adds a new private method  `waitIoComplete` on the `LinuxProcess` type.
This method is called internally when the user calls `wait` for a process - and it tries to give the IO streams some time to clear their buffers.
Internally, this method sets up an `AsyncStream` down which an item is sent when the vsock connection for either stdout/stderr is terminated.
We get this termination signal when the readability handler for the associated fd fires with a no available data.
Inside the guest - once we are done relaying the IO from the process into the socket connection, we close the socket fd which triggers the above.
All this logic is wrapped around a timeout of 3 seconds, just to ensure the method does not block forever.

Add a way to detect if a process' io has completed

---

Package.swift

Building Swift-Syntax can be time-consuming, but this issue has been resolved in the latest version by using a prebuilt binary. This improvement enhances CI build times and the overall quality of the package.
I’ve kept the version at 600 for compatibility reasons, but it might be possible to start from 601 as well.
Please let me know.
Thanks

build: extend the swift-syntax version range

---

vminitd/Sources/vminitd/Server+GRPC.swift

The rootfs should be mounted by this point in oci alteration code.

Vminitd: Remove unneeded mkdir

---

Sources/ContainerizationOCI/Client/RegistryClient+Error.swift
Sources/ContainerizationOCI/Client/RegistryClient+Fetch.swift
Sources/ContainerizationOCI/Client/RegistryClient+Push.swift
Sources/ContainerizationOCI/Client/RegistryClient.swift

Also creates an `ErrorResponse` type to model the errors typically returned by a container registry. 
Reference: https://distribution.github.io/distribution/spec/api/#errors
Example error message:
```
Error: HTTP request to https://ghcr.io/token?client_id=containerization-registry-client&service=ghcr.io&scope=repository:user/image:pull failed with response: 403 Forbidden. Reason: {"errors":[{"message":"requested access to the resource is denied","code":"DENIED"}]}
```

More informative errors from RegistryClient

---

Sources/ContainerizationOCI/Content/ContentWriter.swift

The digest is calculated based on written json data, but JSONEncoder doesn't preserve order bby default, so the digest is not consistent.

Sort keys in image index to keep the digest consistent

---

.github/workflows/containerization-build-template.yml

Constrains the buildAndTest job to only run on the `apple/containerization` repository due to Runner constraints.
Simplest solution - fixes #132

limits buildAndTest to Apple repository

---

Sources/ContainerizationArchive/Reader.swift
Sources/ContainerizationEXT4/EXT4Reader+Export.swift
Sources/ContainerizationOCI/Client/RegistryClient.swift

Continue the allocations journey for anything that is in the codepaths for pulling images. This time there's a couple spots in archive and ext4 we can get rid of some copies.

Containerization: Reduce allocations for image subsystems

---

Sources/ContainerizationOCI/Client/RegistryClient+Token.swift
Sources/ContainerizationOCI/Client/RegistryClient.swift
Tests/ContainerizationOCITests/AuthChallengeTests.swift
Tests/ContainerizationOCITests/RegistryClientTests.swift

There was a bug where the `www-authenticate` header in the HTTP response from a registry would not be parsed accurately.
Specifically, if the header value had more than one `<space>` character, the entire header would be ignored. This PR fixes this bug and adds unit test to detect this in the future.
Fixes https://github.com/apple/container/issues/240
And most likely fixes https://github.com/apple/container/issues/237

Better parsing for www-authenticate headers

---

vminitd/Makefile

This PR resolves the following error for new users:
```
% make cross-prep
Installing Swiftly...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 8549k  100 8549k    0     0  14.7M      0 --:--:-- --:--:-- --:--:-- 14.8M
installer: Package name is 
installer: Installing at base path /Users/Dmitry
installer: The install was successful.
Welcome to swiftly, the Swift toolchain manager for Linux and macOS!
Please read the following information carefully before proceeding with the installation. If you
wish to customize the steps performed during the installation process, refer to 'swiftly init -h'
for configuration options.
Swiftly installs files into the following locations:
/Users/Dmitry/.swiftly - Directory for …
```

Fix the Swiftly bin path

---

Makefile

This PR allows using `make docs` without manually removing the existing `_site` folder.

Regenerate documentation on `make docs`

---

Tests/SendablePropertyMacrosTests/SendablePropertyMacrosTests.swift

This PR fixes compilation warnings observed in:
```
swift -v --version
Apple Swift version 6.2-dev (LLVM 5fbc818cf26c90b, Swift 2e1897356956e43)
Target: arm64-apple-macosx26.0
/Users/Dmitry/Library/Developer/Toolchains/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-06-17-a.xctoolchain/usr/bin/swift-frontend --version
Apple Swift version 6.2-dev (LLVM 5fbc818cf26c90b, Swift 2e1897356956e43)
Target: arm64-apple-macosx26.0
Build config: +assertions
```

Fix compilation warnings

---

Sources/Integration/ProcessTests.swift
vminitd/Sources/vminitd/ManagedProcess.swift
vminitd/Sources/vminitd/ProcessSupervisor.swift
vminitd/Sources/vminitd/StandardIO.swift
vminitd/Sources/vminitd/TerminalIO.swift

run cleanupRelay only once in TerminalIO and StandardIO

---

Makefile
vminitd/Makefile
vminitd/Sources/vmexec/ExecCommand.swift
vminitd/Sources/vmexec/RunCommand.swift
vminitd/Sources/vmexec/vmexec.swift
vminitd/Sources/vminitd/StandardIO.swift
vminitd/Sources/vminitd/TerminalIO.swift

Reverts f9198d6ff79abb53ed51a87f9ce7afe49e08f48f
We can explore better approaches to some of the targets, but for now lets revert as it interferes with being able to build even if we have local changes.

Makefile: Revert recent reworking

---

vminitd/Sources/vmexec/ExecCommand.swift
vminitd/Sources/vmexec/RunCommand.swift
vminitd/Sources/vmexec/vmexec.swift

We don't chown the container's stdio today.

vmexec: Set perms on stdio

---

.github/ISSUE_TEMPLATE/01-bug.yml
.github/ISSUE_TEMPLATE/02-feature.yml

Tags on the repo should be a way to classify an item instead of denoting workflow or status of the item. Remove the addition of the triage label on bug and feature issues.
Related to https://github.com/apple/container/pull/262

Remove use of triage label

---

Sources/Containerization/VZVirtualMachineInstance.swift

I don't believe we need this for anything here (maybe we once did).

Remove preconcurrency from Virtualization import

---

Sources/Containerization/Image/Image.swift
Sources/Containerization/Image/InitImage.swift
Sources/Containerization/Image/Unpacker/EXT4Unpacker.swift
Sources/Containerization/Image/Unpacker/Unpacker.swift
Sources/Integration/Suite.swift
Sources/cctl/ContainerStore.swift
Sources/cctl/ImageCommand.swift

Creates a new Unpacker protocol that defines a single method
```
func unpack(_ image: Image, for platform: Platform, at path: URL, progress: ProgressHandler?) async throws -> Mount
```
This change also removes the `unpack(...)` method from the Image type.
Before
```
let mount = try await image.unpack(for: platform, at: path)
```
After
```
let unpacker = EXT4Unpacker(blockSizeInBytes: 2.gib())
let mount = try await unpacker.unpack(image, for: platform, at: path)
```

Create unpacker protocol + ext4 unpacker

---

.spi.yml

adds configuration to SwiftPackageIndex manifest to request builds happen explicitly on Swift 6.2 vs whatever the current default it

update SPI manifest to build on 6.2 only

---

Sources/Containerization/Agent/Vminitd.swift
Sources/Containerization/LinuxContainer.swift
Sources/Containerization/LinuxProcess.swift
Sources/Containerization/SandboxContext/SandboxContext.grpc.swift
Sources/Containerization/SandboxContext/SandboxContext.pb.swift
Sources/Containerization/SandboxContext/SandboxContext.proto
Sources/Containerization/VirtualMachineAgent.swift
Sources/Integration/ProcessTests.swift
Sources/Integration/Suite.swift
vminitd/Sources/vminitd/ManagedContainer.swift
vminitd/Sources/vminitd/ManagedProcess.swift
vminitd/Sources/vminitd/Server+GRPC.swift

This allows the user the ability to raise an EOF for the containers stdin. Today there's no way to close stdin so something as simple as "cat" and relying on EOF to move the process forward doesn't work

LinuxContainer: Add ability to close stdin

---

Sources/ContainerizationOS/Keychain/KeychainQuery.swift

There have been a few issues filed in container [here](https://github.com/apple/container/issues/254) and [here](https://github.com/apple/container/issues/321), where people are unable to pull or push to registries despite a successful login to that registry. 
Making this enum public so that we can get the error in container and handle it correctly.

Make KeychainQuery errors type public

---

Sources/Containerization/LinuxContainer.swift
Sources/SendableProperty/SendableProperty.swift
Sources/SendableProperty/SendablePropertyUnchecked.swift
Sources/SendableProperty/Synchronized.swift
Sources/SendablePropertyMacros/SendablePropertyError.swift
Sources/SendablePropertyMacros/SendablePropertyMacro.swift
Sources/SendablePropertyMacros/SendablePropertyMacroUnchecked.swift
Sources/SendablePropertyMacros/SendablePropertyPlugin.swift
Tests/SendablePropertyTests/SendablePropertyTests.swift

- The `@SendableProperty` macro now checks for supported types to prevent a misuse with unsupported types like structs, dictionaries, and arrays
- The new `@SendablePropertyUnchecked` can be used with classes and enums

Check for supported types in the `@SendableProperty` macro

---

Sources/Containerization/Image/ImageStore/ImageStore+Import.swift
Sources/ContainerizationOCI/AnnotationKeys.swift

In general I believe it's clever to synthesize an index for single-platform image manifest, but we still need a way to distinguish it. Add a dedicated annotation is the slightest change I've come up with, and it's also OCI compliant. With this change come in, we can work around https://github.com/apple/container/issues/212 and imitate the behavior of other runtime with `container`.
Note that since `cctl` is meant to be a dedicated tool for inspecting the Containerization framework itself, I didn't apply the indirection for it, and it will be as-is with the genuine storage.

Add a `com.apple.containerization.index.indirect` annotation to distinguish synthesized index

---

Sources/CShim/exec_command.c
Sources/CShim/include/exec_command.h

Instead of looping through from minimum fd -> rlimit max, we can close_range(2) or read /proc/self/fd on Linux, and read /dev/fd on macOS.

ContainerizationOS: Speed up fd closes

---

Sources/Containerization/LinuxContainer.swift
Sources/Containerization/LinuxProcess.swift
Sources/Containerization/VZVirtualMachineManager.swift
Sources/Integration/ProcessTests.swift
Sources/Integration/VMTests.swift
Sources/cctl/ContainerStore.swift
Sources/cctl/RunCommand.swift

This is a fairly large reworking, but it gets rid of something that has plagued this since release which is the properties needing to be locked to be Sendable compliant. This was somewhat of a copout because we mostly know there's not a great deal of ways to have misused the setup today, but alas we'd need to either mark the type as `@unchecked` or just find a different route for setting the configuration. This change:
Exposes the underlying Configuration type that today only housed things that aren't on the OCI spec. I'd love to just expose the OCI spec, but we don't (and possibly never will) support everything on the spec, so exposing it to be freely modified would be a bit odd. Now everything related to the container is configured on this type, and the same goes for execs.

LinuxContainer/LinuxProcess: Rework supplying configuration

---

Sources/Containerization/AttachedFilesystem.swift

The type copy is the exact same on any of the types, just move it outside of the cases like we have for options and destination.

Chore: Simplify AttachedFilesystem constructor

---

Sources/ContainerizationIO/ReadStream.swift

This PR only changes names of private properties to align them with the naming standards.

Standardize property names in `ReadStream`

---

Sources/Containerization/LinuxContainer.swift
Sources/Integration/Suite.swift
Sources/Integration/VMTests.swift

After the container is stopped it's a bit odd how we don't allow the object to be restarted. If someone wanted to continuously rerun the same container they'd need to make a new object every time even though all guest state is blown away on stop() so it's a clean slate.
This change makes it so that you can create+start again after stop (although create stands out like a sore thumb now as stop -> create is just strange).

LinuxContainer: Allow reuse after being stopped

---

Sources/Containerization/Agent/Vminitd.swift
Sources/cctl/RunCommand.swift
vminitd/Sources/vminitd/Application.swift

This reverts commit 5f7dcd2a1687d28ee5cb28e274d23acf57f760fc. Rosetta is setup at /run because the guest rootfs is ro, and unfortunately this happens prior to LinuxContainer getting to mount any of this. I'm not super happy about this, but we can figure something out later.
Additionally this adds a rosetta flag to cctl so we can quickly spotcheck things like this again.

Revert "Vminitd: Remove special cased /run mount (#233)"

---

Sources/ContainerizationOS/Socket/Socket.swift

While individual accesses were properly mutex-protected, the logical operations were not atomic, leading to a potential inconsistency in a multi-threaded environment. Multiple separate `state.withLock` calls created race windows. With the proposed changes, single atomic operations check and update the state together.

Eliminate race windows in the `Socket` class

---

Makefile
Sources/Containerization/NATNetworkInterface.swift

This PR replaces public computed properties with setters in the `NATNetworkInterface` class with constants to avoid using locks in the setters. A new instance of `NATNetworkInterface` should be created to change these values.

Replace public computed properties with locks in setters

---

Sources/Containerization/Image/ImageStore/ImageStore+ReferenceManager.swift
Sources/Containerization/TimeSyncer.swift
vminitd/Sources/vminitd/OSFile+Splice.swift

This PR modifies the access level of certain mutable properties to ensure their thread-safe usage. It doesn't address https://github.com/apple/containerization/issues/246 at this time.

Ensure mutable properties aren't accessed outside their intended thread-safe usage patterns

---

vminitd/Sources/vmexec/RunCommand.swift

Closes #251
We use devtmpfs today so our pal /dev/rtc0 is there. It's typical to have a /dev/rtc symlink to /dev/rtc0.

Add /dev/rtc symlink

---

Sources/Integration/Suite.swift
Sources/Integration/VMTests.swift
Sources/cctl/RunCommand.swift
vminitd/Sources/vmexec/Console.swift
vminitd/Sources/vmexec/ExecCommand.swift
vminitd/Sources/vmexec/Mount.swift
vminitd/Sources/vmexec/RunCommand.swift
vminitd/Sources/vmexec/vmexec.swift
vminitd/Sources/vminitd/IOPair.swift
vminitd/Sources/vminitd/ManagedProcess.swift
vminitd/Sources/vminitd/StandardIO.swift
vminitd/Sources/vminitd/TerminalIO.swift

Closes #246 
Closes #145
We need to allocate the pty in the containers ns otherwise you run into funny outcomes later. This change additionally mounts /dev/console by binding the pty opened in the containers namespace onto it. Today /dev/console is solely from devtmpfs which points at /dev/hvc0, or the virtio serial console. This causes systemds output to go to serial/the bootlog
instead of what folks would expect. This should make systemd like us a lot more than it does today.
Another large change that was somewhat required here is the changes in IOPair. EPOLLHUP on a pty is deceptively weird to handle as it could be reopened, so we can't do what we were doing today and just close all the fds. To remedy this I skip exiting on HUP for pty's and instead just cleanup at process exit time, …

vminitd: Proper pty setup / mount /dev/console

---

Sources/Containerization/Agent/Vminitd.swift
Sources/Containerization/LinuxContainer.swift
vminitd/Sources/vminitd/CgroupManager.swift
vminitd/Sources/vminitd/ManagedContainer.swift
vminitd/Sources/vminitd/ManagedProcess.swift

We currently weren't doing any cgroup setup whatsoever. For the most part this doesn't matter too much, however certain images that may fool around with cgroups don't like this :). Lets do the bare minimum these expect which is to at least have the process running in a nested cg and not apart of the root cg.

vminitd: Add init and execs to cgroup

---

Makefile
Sources/Containerization/Image/Unpacker/EXT4Unpacker.swift
Sources/cctl/RootfsCommand.swift

This refactors the rootfs command to produce an image and have the ability to create an ext4 formatted block of the init filesystem directly from the command.
closes #220

add ability to export initfs as block

---

vminitd/Sources/vmexec/ExecCommand.swift
vminitd/Sources/vminitd/Cgroup2Manager.swift
vminitd/Sources/vminitd/ManagedContainer.swift
vminitd/Sources/vminitd/ManagedProcess.swift
vminitd/Sources/vminitd/Server+GRPC.swift

Systemd loves to move the root cgroups processes to one it created named /init.scope and then write the root cgs subtree_control file. Because of this we can't just add exec processes to the cg we made for the container anymore as we'll get EBUSY. We should follow where the init processes cg is actually at (/proc/pid/cgroup) and add it there.

Cgroup2Manager: Various adjustments

---

vminitd/Sources/vminitd/ManagedContainer.swift

We had a log for the initial oci runtime spec, but we don't log anything for execed processes. This makes it hard to look into issues that may be due to just a mistake in the spec and nothing wrong with the actual logic of the program.

vminitd: Log spec for exec processes

---

vminitd/Sources/vmexec/ExecCommand.swift
vminitd/Sources/vmexec/RunCommand.swift
vminitd/Sources/vminitd/ManagedProcess.swift

Today, because we don't wait for execvpe to finish to continue onwards, it's possible that if you did an exec quick enough after starting an init process for a container, that you could join the init processes namespaces before pivot_root has taken place which is quite fun. Let's wait for exec to finish (or an error to occur) to prevent this.

vminitd: Wait for execvpe to return to continue

---

vminitd/Sources/vminitd/Server.swift

We shouldn't need this import anymore
cc: @crosbymichael

vminitd: Removed extraneous import

---

Tests/ContainerizationTests/DNSTests.swift
Tests/ContainerizationTests/HashTests.swift
Tests/ContainerizationTests/HostsTests.swift
Tests/ContainerizationTests/ImageTests.swift
Tests/ContainerizationTests/KernelTests.swift
Tests/ContainerizationTests/LinuxContainerTests.swift
Tests/ContainerizationTests/MountTests.swift

Add additional tests, with varying levels of utility.
Before: Overall Code Coverage: 41.73%
After: Overall Code Coverage: 42.95%

containerization: Add additional tests

---

Sources/ContainerizationOCI/Client/RegistryClient+Fetch.swift

When an image is broken, `container-core-images` may crash with:
```
Application Specific Information:
_NIOFileSystem/SystemFileHandle.swift:131: Fatal error: Leaking file descriptor: the handle for '/Users/Dmitry/Library/Application Support/com.apple.container/content/ingest/03144D38-D98D-4833-9E0C-60229BF653D9/.tmp-MIB1oc' MUST be closed or detached with 'close()' or 'detachUnsafeFileDescriptor()' before the final reference to the handle is dropped.
Thread 9 Crashed:
0   libswiftCore.dylib            	       0x1adbfe110 _assertionFailure(_:_:file:line:flags:) + 176
1   container-core-images         	       0x105773628 closure #1 in SystemFileHandle.deinit + 424 (SystemFileHandle.swift:131)
2   container-core-images         	       0x10577365c partial apply for closure #1 in …
```

Prevent a leak detection crash when `close()` fails

---

Sources/Containerization/ExitStatus.swift

Client code may want to return ExitStatus from
functions that return a containerization process
return code, or -1 for caught exceptions.

Adds public init for ExitStatus.

---

README.md
kernel/Dockerfile
kernel/Makefile
kernel/README.md
kernel/build.sh
kernel/image/Dockerfile

Fixes #296
Today the kernel subdirectory is somewhat useless. The dockerfile we had tried to use an image that isn't actually on ghcr, so everything would kind of just crap out. This change swaps things so that we build a local image that has all the bits needed to compile the kernel, and then uses that image to build the resulting kernel and plop it in the current working directory. This change does add a reliance on `container` being installed however, but for folks that need to build a custom kernel this doesn't seem like too much of an issue to me.

Kernel: Fix `make`

---

Sources/Containerization/InterfaceStatistics.swift
Sources/Containerization/SandboxContext/SandboxContext.grpc.swift
Sources/Containerization/SandboxContext/SandboxContext.pb.swift
Sources/Containerization/SandboxContext/SandboxContext.proto
Sources/Containerization/VirtualMachineAgent.swift
Sources/Containerization/Vminitd.swift
Sources/ContainerizationNetlink/NetlinkSession.swift
Sources/ContainerizationNetlink/Types.swift
vminitd/Sources/vminitd/Server+GRPC.swift

Adds support for grabbing stats for an iface. This will be surfaced in a coming change to get container level statistics from the guest, where one field will be network stats.

Netlink: Add stats support
